### ISSUE TITLE
segfault when providing config file

### ISSUE THREAD

**Issue by sophiakoulen** [BPhilagor/WebServ#12]
This config file:
```
server 1 {
	listen = 127.0.0.1:8080
}
```
Generates a segfault. I can't figure out what makes it different that the srv.config file that we have.

**Comment by znichola** [comment]
the problem is here `*config.getServerForHostPortAndHostName(foo, "asd")` we are calling this function and not checking if the pointer returned in `NULL`. T

there is no match for the host/port and name, so the return is null. We sort of came to the conclusion it's easiest like this, but idk it's really so. Another possible option was to use the [null object pattern](https://en.wikipedia.org/wiki/Null_object_pattern) but this also feels a bit hacky. idk.

**Comment by znichola** [comment]
refactored away
